UndefinedError
jinja2.exceptions.UndefinedError: 'users_db' is undefined

Traceback (most recent call last)
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/flask/app.py", line 1478, in __call__
return self.wsgi_app(environ, start_response)
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/flask/app.py", line 1458, in wsgi_app
response = self.handle_exception(e)
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
response = self.full_dispatch_request()
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/home/runner/workspace/main.py", line 124, in dashboard
return render_template('dashboard.html')
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/flask/templating.py", line 152, in render_template
return _render(app, template, context)
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/flask/templating.py", line 133, in _render
rv = template.render(context)
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/home/runner/workspace/templates/dashboard.html", line 178, in top-level template code
{% for login in users_db[session['email']]['login_history'][-5:]|reverse %}
File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/jinja2/environment.py", line 466, in getitem
return obj[argument]Open an interactive python shell in this frame
jinja2.exceptions.UndefinedError: 'users_db' is undefined
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Broug